/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InstallationTargetRevisionReply struct {
	Revision *ApiObjectStandardIdentifier `json:"revision,omitempty" xml:"revision"`
	// The name of the installation target.
	TargetName string `json:"target-name,omitempty" xml:"target-name"`
	// Installation target unique identifier.
	TargetUid string `json:"target-uid,omitempty" xml:"target-uid"`
}
