/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Gateway VPN settings.
type VpnSettingsReply struct {
	// N/A
	MaximumConcurrentIkeNegotiations int32 `json:"maximum-concurrent-ike-negotiations,omitempty" xml:"maximum-concurrent-ike-negotiations"`
	// N/A
	MaximumConcurrentTunnels int32 `json:"maximum-concurrent-tunnels,omitempty" xml:"maximum-concurrent-tunnels"`
}
