/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WorkSessionPurgeRequest struct {
	// The number of newest sessions to preserve, by the sessions's publish date.
	NumberOfSessionsToPreserve int32 `json:"number-of-sessions-to-preserve" xml:"number-of-sessions-to-preserve"`
	// The date until which sessions are preserved, by the sessions's publish date. ISO 8601. If timezone isn't specified in the input, the Management server's timezone is used.
	PreserveToDate string `json:"preserve-to-date,omitempty" xml:"preserve-to-date"`
}
