/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NetworkInterfaceReply struct {
	// N/A
	AntiSpoofing bool `json:"anti-spoofing,omitempty" xml:"anti-spoofing"`
	AntiSpoofingSettings *AntiSpoofingSettingsReply `json:"anti-spoofing-settings,omitempty" xml:"anti-spoofing-settings"`
	// Color of the object. Should be one of existing colors.
	Color string `json:"color,omitempty" xml:"color"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	// Object icon.
	Icon string `json:"icon,omitempty" xml:"icon"`
	// IPv4 address.
	Ipv4Address string `json:"ipv4-address,omitempty" xml:"ipv4-address"`
	// IPv4 network mask length.
	Ipv4MaskLength int32 `json:"ipv4-mask-length,omitempty" xml:"ipv4-mask-length"`
	// IPv4 network mask.
	Ipv4NetworkMask string `json:"ipv4-network-mask,omitempty" xml:"ipv4-network-mask"`
	// IPv6 address.
	Ipv6Address string `json:"ipv6-address,omitempty" xml:"ipv6-address"`
	// IPv6 network mask length.
	Ipv6MaskLength int32 `json:"ipv6-mask-length,omitempty" xml:"ipv6-mask-length"`
	// IPv6 network mask.
	Ipv6NetworkMask string `json:"ipv6-network-mask,omitempty" xml:"ipv6-network-mask"`
	// Interface name.
	Name string `json:"name,omitempty" xml:"name"`
	// N/A
	SecurityZone bool `json:"security-zone,omitempty" xml:"security-zone"`
	SecurityZoneSettings *SecurityZoneSettingsReply `json:"security-zone-settings,omitempty" xml:"security-zone-settings"`
	// Topology configuration.
	Topology string `json:"topology,omitempty" xml:"topology"`
	// Shows the automatic topology calculation.
	TopologyAutomaticCalculation string `json:"topology-automatic-calculation,omitempty" xml:"topology-automatic-calculation"`
	TopologySettings *InternalTopologySettingsReply `json:"topology-settings,omitempty" xml:"topology-settings"`
}
