/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InstallationTargetRevisionFullReply struct {
	// If this target is a cluster, this list shows a revision which was installed on each cluster member.
	ClusterMembersRevision []InstallationTargetRevisionReply `json:"cluster-members-revision,omitempty" xml:"cluster-members-revision"`
	Revision *ApiObjectStandardIdentifier `json:"revision,omitempty" xml:"revision"`
	// The name of the installation target.
	TargetName string `json:"target-name,omitempty" xml:"target-name"`
	// Installation target unique identifier.
	TargetUid string `json:"target-uid,omitempty" xml:"target-uid"`
}
