/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ThreatExceptionRequestEdit struct {
	// Action-the enforced profile.
	Action string `json:"action,omitempty" xml:"action"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	Destination *Add `json:"destination,omitempty" xml:"destination"`
	// True if negate is set for destination.
	DestinationNegate bool `json:"destination-negate,omitempty" xml:"destination-negate"`
	// The level of detail for some of the fields in the response can vary from showing only the UID value of the object to a fully detailed representation of the object.
	DetailsLevel string `json:"details-level,omitempty" xml:"details-level"`
	// Enable/Disable the rule.
	Enabled bool `json:"enabled,omitempty" xml:"enabled"`
	// The name of the exception-group.
	ExceptionGroupName string `json:"exception-group-name,omitempty" xml:"exception-group-name"`
	// The UID of the exception-group.
	ExceptionGroupUid string `json:"exception-group-uid" xml:"exception-group-uid"`
	// N/A
	ExceptionNumber int32 `json:"exception-number,omitempty" xml:"exception-number"`
	// Apply changes ignoring errors. You won't be able to publish such a changes. If ignore-warnings flag was omitted - warnings will also be ignored.
	IgnoreErrors bool `json:"ignore-errors,omitempty" xml:"ignore-errors"`
	// Apply changes ignoring warnings.
	IgnoreWarnings bool `json:"ignore-warnings,omitempty" xml:"ignore-warnings"`
	InstallOn *Add `json:"install-on,omitempty" xml:"install-on"`
	// Layer that the rule belongs to identified by the name or UID.
	Layer string `json:"layer" xml:"layer"`
	// The name of the exception.
	Name string `json:"name" xml:"name"`
	// New name of the object.
	NewName string `json:"new-name,omitempty" xml:"new-name"`
	// New position in the rulebase.
	NewPosition int32 `json:"new-position,omitempty" xml:"new-position"`
	ProtectedScope *Add `json:"protected-scope,omitempty" xml:"protected-scope"`
	// True if negate is set for Protected Scope.
	ProtectedScopeNegate bool `json:"protected-scope-negate,omitempty" xml:"protected-scope-negate"`
	ProtectionOrSite *Add `json:"protection-or-site,omitempty" xml:"protection-or-site"`
	// The name of the parent rule.
	RuleName string `json:"rule-name,omitempty" xml:"rule-name"`
	// The position in the rulebase of the parent rule.
	RuleNumber int32 `json:"rule-number,omitempty" xml:"rule-number"`
	// The UID of the parent rule.
	RuleUid string `json:"rule-uid" xml:"rule-uid"`
	Service *Add `json:"service,omitempty" xml:"service"`
	// True if negate is set for Service.
	ServiceNegate bool `json:"service-negate,omitempty" xml:"service-negate"`
	Source *Add `json:"source,omitempty" xml:"source"`
	// True if negate is set for source.
	SourceNegate bool `json:"source-negate,omitempty" xml:"source-negate"`
	// Packet tracking.
	Track string `json:"track,omitempty" xml:"track"`
	// Object unique identifier.
	Uid string `json:"uid" xml:"uid"`
}
