/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Web Server configuration.
type WebServerReply struct {
	// Server additional ports.
	AdditionalPorts []string `json:"additional-ports,omitempty" xml:"additional-ports"`
	// Application engines of this web server.
	ApplicationEngines []string `json:"application-engines,omitempty" xml:"application-engines"`
	// Whether server listens to standard port.
	ListenStandardPort bool `json:"listen-standard-port,omitempty" xml:"listen-standard-port"`
	// Operating System.
	OperatingSystem string `json:"operating-system,omitempty" xml:"operating-system"`
	// Network object which protects this server identified by the name or UID.
	ProtectedBy string `json:"protected-by,omitempty" xml:"protected-by"`
	// Server standard port number.
	StandardPortNumber int32 `json:"standard-port-number,omitempty" xml:"standard-port-number"`
}
