/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VpnStarCommunityReply struct {
	// Collection of Gateway objects representing center gateways identified by the name or UID. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	CenterGateways []ApiObjectStandardIdentifier `json:"center-gateways,omitempty" xml:"center-gateways"`
	// Color of the object. Should be one of existing colors.
	Color string `json:"color,omitempty" xml:"color"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	Domain *ApiDomainIdentifier `json:"domain,omitempty" xml:"domain"`
	// The encryption method to be used.
	EncryptionMethod string `json:"encryption-method,omitempty" xml:"encryption-method"`
	// The encryption suite to be used.
	EncryptionSuite string `json:"encryption-suite,omitempty" xml:"encryption-suite"`
	// Object icon.
	Icon string `json:"icon,omitempty" xml:"icon"`
	IkePhase1 *IkeP1Reply `json:"ike-phase-1,omitempty" xml:"ike-phase-1"`
	IkePhase2 *IkeP2Reply `json:"ike-phase-2,omitempty" xml:"ike-phase-2"`
	// Indicates whether the meshed community is in center.
	MeshCenterGateways bool `json:"mesh-center-gateways,omitempty" xml:"mesh-center-gateways"`
	MetaInfo *MetaInfoForTopLevelReply `json:"meta-info,omitempty" xml:"meta-info"`
	// Object name. Should be unique in the domain.
	Name string `json:"name,omitempty" xml:"name"`
	// Indicates whether the object is read-only.
	ReadOnly bool `json:"read-only,omitempty" xml:"read-only"`
	// Collection of Gateway objects representing satellite gateways identified by the name or UID. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	SatelliteGateways []ApiObjectStandardIdentifier `json:"satellite-gateways,omitempty" xml:"satellite-gateways"`
	// Shared secrets for external gateways.
	SharedSecrets []SharedSecretReply `json:"shared-secrets,omitempty" xml:"shared-secrets"`
	// Collection of tag objects identified by the name or UID. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	Tags []ApiObjectStandardIdentifier `json:"tags,omitempty" xml:"tags"`
	// Type of the object.
	Type_ string `json:"type,omitempty" xml:"type"`
	// Object unique identifier.
	Uid string `json:"uid,omitempty" xml:"uid"`
	// Indicates whether the shared secret should be used for all external gateways.
	UseSharedSecret bool `json:"use-shared-secret,omitempty" xml:"use-shared-secret"`
}
