/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Indirect usage of the object.
type WhereUsedReportReply struct {
	// Usage in Access Control Policy rules. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	AccessControlRules []ApiObjectStandardIdentifier `json:"access-control-rules,omitempty" xml:"access-control-rules"`
	// Usage in Network Address Translation Policy rules. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	NatRules []ApiObjectStandardIdentifier `json:"nat-rules,omitempty" xml:"nat-rules"`
	// Usage in objects. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	Objects []ApiObjectStandardIdentifier `json:"objects,omitempty" xml:"objects"`
	// Usage in Threat Prevention Policy rules. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	ThreatPreventionRules []ApiObjectStandardIdentifier `json:"threat-prevention-rules,omitempty" xml:"threat-prevention-rules"`
	// Total usage number.
	Total int32 `json:"total,omitempty" xml:"total"`
}
