/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TimeRequestEdit struct {
	// Color of the object. Should be one of existing colors.
	Color string `json:"color,omitempty" xml:"color"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	// The level of detail for some of the fields in the response can vary from showing only the UID value of the object to a fully detailed representation of the object.
	DetailsLevel string `json:"details-level,omitempty" xml:"details-level"`
	End *TimeObjectForRequest `json:"end,omitempty" xml:"end"`
	// End never.
	EndNever bool `json:"end-never,omitempty" xml:"end-never"`
	Groups *Add `json:"groups,omitempty" xml:"groups"`
	// Hours recurrence. Note: Each gateway may interpret this time differently according to its time zone.
	HoursRanges []HourRange `json:"hours-ranges,omitempty" xml:"hours-ranges"`
	// Apply changes ignoring errors. You won't be able to publish such a changes. If ignore-warnings flag was omitted - warnings will also be ignored.
	IgnoreErrors bool `json:"ignore-errors,omitempty" xml:"ignore-errors"`
	// Apply changes ignoring warnings.
	IgnoreWarnings bool `json:"ignore-warnings,omitempty" xml:"ignore-warnings"`
	// Object name.
	Name string `json:"name,omitempty" xml:"name"`
	// New name of the Time object. Cannot be more than 11 characters. Should be unique in the domain.
	NewName string `json:"new-name,omitempty" xml:"new-name"`
	Recurrence *DayRecurrence `json:"recurrence,omitempty" xml:"recurrence"`
	Start *TimeObjectForRequest `json:"start,omitempty" xml:"start"`
	// Start immediately.
	StartNow bool `json:"start-now,omitempty" xml:"start-now"`
	Tags *Add `json:"tags,omitempty" xml:"tags"`
	// Object unique identifier.
	Uid string `json:"uid" xml:"uid"`
}
