/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Hits count object.
type HitsReply struct {
	FirstDate *ApiDateReply `json:"first-date,omitempty" xml:"first-date"`
	LastDate *ApiDateReply `json:"last-date,omitempty" xml:"last-date"`
	// N/A
	Level string `json:"level,omitempty" xml:"level"`
	// N/A
	Percentage string `json:"percentage,omitempty" xml:"percentage"`
	// N/A
	Value int32 `json:"value,omitempty" xml:"value"`
}
