/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProfileReply struct {
	// Protections with this performance impact only will be activated in the profile.
	ActiveProtectionsPerformanceImpact string `json:"active-protections-performance-impact,omitempty" xml:"active-protections-performance-impact"`
	// Protections with this severity only will be activated in the profile.
	ActiveProtectionsSeverity string `json:"active-protections-severity,omitempty" xml:"active-protections-severity"`
	// Is Anti-Bot blade activated.
	AntiBot bool `json:"anti-bot,omitempty" xml:"anti-bot"`
	// Is Anti-Virus blade activated.
	AntiVirus bool `json:"anti-virus,omitempty" xml:"anti-virus"`
	// Color of the object. Should be one of existing colors.
	Color string `json:"color,omitempty" xml:"color"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	// Action for protections with high confidence level.
	ConfidenceLevelHigh string `json:"confidence-level-high,omitempty" xml:"confidence-level-high"`
	// Action for protections with low confidence level.
	ConfidenceLevelLow string `json:"confidence-level-low,omitempty" xml:"confidence-level-low"`
	// Action for protections with medium confidence level.
	ConfidenceLevelMedium string `json:"confidence-level-medium,omitempty" xml:"confidence-level-medium"`
	Domain *ApiDomainIdentifier `json:"domain,omitempty" xml:"domain"`
	// Activate protections by these extended attributes.
	ExtendedAttributesToActivate []IpsAdditionalPropertiesReply `json:"extended-attributes-to-activate,omitempty" xml:"extended-attributes-to-activate"`
	// Deactivate protections by these extended attributes.
	ExtendedAttributesToDeactivate []IpsAdditionalPropertiesReply `json:"extended-attributes-to-deactivate,omitempty" xml:"extended-attributes-to-deactivate"`
	// Object icon.
	Icon string `json:"icon,omitempty" xml:"icon"`
	// Indicators whose action will be overridden in this profile.
	IndicatorOverrides []ProfileIndicatorOverrideRequest `json:"indicator-overrides,omitempty" xml:"indicator-overrides"`
	// Is IPS blade activated.
	Ips bool `json:"ips,omitempty" xml:"ips"`
	IpsSettings *IpsSettingsReply `json:"ips-settings,omitempty" xml:"ips-settings"`
	MaliciousMailPolicySettings *MailSettingsReply `json:"malicious-mail-policy-settings,omitempty" xml:"malicious-mail-policy-settings"`
	MetaInfo *MetaInfoForTopLevelReply `json:"meta-info,omitempty" xml:"meta-info"`
	// Object name. Should be unique in the domain.
	Name string `json:"name,omitempty" xml:"name"`
	// Overrides per profile for this protection.
	Overrides []AllActivationsByProtectionReply `json:"overrides,omitempty" xml:"overrides"`
	// Indicates whether the object is read-only.
	ReadOnly bool `json:"read-only,omitempty" xml:"read-only"`
	// Collection of tag objects identified by the name or UID. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	Tags []ApiObjectStandardIdentifier `json:"tags,omitempty" xml:"tags"`
	// Is Threat Emulation blade activated.
	ThreatEmulation bool `json:"threat-emulation,omitempty" xml:"threat-emulation"`
	// Type of the object.
	Type_ string `json:"type,omitempty" xml:"type"`
	// Object unique identifier.
	Uid string `json:"uid,omitempty" xml:"uid"`
	// Whether to activate/deactivate IPS protections according to the extended attributes.
	UseExtendedAttributes bool `json:"use-extended-attributes,omitempty" xml:"use-extended-attributes"`
	// Indicates whether the profile should make use of indicators.
	UseIndicators bool `json:"use-indicators,omitempty" xml:"use-indicators"`
}
