/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccessRoleRequestNew struct {
	// Color of the object. Should be one of existing colors.
	Color string `json:"color,omitempty" xml:"color"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	// The level of detail for some of the fields in the response can vary from showing only the UID value of the object to a fully detailed representation of the object.
	DetailsLevel string `json:"details-level,omitempty" xml:"details-level"`
	// Apply changes ignoring errors. You won't be able to publish such a changes. If ignore-warnings flag was omitted - warnings will also be ignored.
	IgnoreErrors bool `json:"ignore-errors,omitempty" xml:"ignore-errors"`
	// Apply changes ignoring warnings.
	IgnoreWarnings bool `json:"ignore-warnings,omitempty" xml:"ignore-warnings"`
	// Machines that can access the system.
	Machines string `json:"machines,omitempty" xml:"machines"`
	// Object name. Should be unique in the domain.
	Name string `json:"name" xml:"name"`
	// Collection of Network objects identified by the name or UID that can access the system.
	Networks string `json:"networks,omitempty" xml:"networks"`
	// Remote access clients identified by name or UID.
	RemoteAccessClients string `json:"remote-access-clients,omitempty" xml:"remote-access-clients"`
	// Collection of tag identifiers.
	Tags string `json:"tags,omitempty" xml:"tags"`
	// Users that can access the system.
	Users string `json:"users,omitempty" xml:"users"`
}
