/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WebApiServerStatusReply struct {
	// N/A
	ApiMoreInfo string `json:"api-more-info,omitempty" xml:"api-more-info"`
	// N/A
	ApiOverallStatus bool `json:"api-overall-status,omitempty" xml:"api-overall-status"`
	// N/A
	ApiPid string `json:"api-pid,omitempty" xml:"api-pid"`
	// N/A
	ApiState string `json:"api-state,omitempty" xml:"api-state"`
	// N/A
	ApiStatus string `json:"api-status,omitempty" xml:"api-status"`
	// N/A
	CpmMoreInfo string `json:"cpm-more-info,omitempty" xml:"cpm-more-info"`
	// N/A
	CpmPid string `json:"cpm-pid,omitempty" xml:"cpm-pid"`
	// N/A
	CpmState string `json:"cpm-state,omitempty" xml:"cpm-state"`
	// N/A
	FwmMoreInfo string `json:"fwm-more-info,omitempty" xml:"fwm-more-info"`
	// N/A
	FwmPid string `json:"fwm-pid,omitempty" xml:"fwm-pid"`
	// N/A
	FwmState string `json:"fwm-state,omitempty" xml:"fwm-state"`
	// Asynchronous task unique identifier.
	TaskId string `json:"task-id,omitempty" xml:"task-id"`
}
