/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ThreatExceptionGroupRequestEdit struct {
	// The threat profile to apply this group to in the case of apply-on threat-rules-with-specific-profile.
	AppliedProfile string `json:"applied-profile,omitempty" xml:"applied-profile"`
	AppliedThreatRules *Add `json:"applied-threat-rules,omitempty" xml:"applied-threat-rules"`
	// An exception group can be set to apply on all threat rules, all threat rules which have a specific profile, or those rules manually chosen by the user.
	ApplyOn string `json:"apply-on,omitempty" xml:"apply-on"`
	// Color of the object. Should be one of existing colors.
	Color string `json:"color,omitempty" xml:"color"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	// The level of detail for some of the fields in the response can vary from showing only the UID value of the object to a fully detailed representation of the object.
	DetailsLevel string `json:"details-level,omitempty" xml:"details-level"`
	// Apply changes ignoring errors. You won't be able to publish such a changes. If ignore-warnings flag was omitted - warnings will also be ignored.
	IgnoreErrors bool `json:"ignore-errors,omitempty" xml:"ignore-errors"`
	// Apply changes ignoring warnings.
	IgnoreWarnings bool `json:"ignore-warnings,omitempty" xml:"ignore-warnings"`
	// Object name.
	Name string `json:"name,omitempty" xml:"name"`
	// New name of the object.
	NewName string `json:"new-name,omitempty" xml:"new-name"`
	Tags *Add `json:"tags,omitempty" xml:"tags"`
	// Object unique identifier.
	Uid string `json:"uid" xml:"uid"`
}
