/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Displays the service group's matched content as ranges of port numbers, in case 'show-as-ranges' is set to true.<br />In this case, the 'members' parameter is omitted.
type PortRanges struct {
	// Objects which are not represented as port numbers and are negated in the given rule - for example if negate is set for the service of this rule. The details-level parameter of the request determines whether they are displayed as UID's or objects.
	ExcludedOthers []interface{} `json:"excluded-others,omitempty" xml:"excluded-others"`
	// Objects which are not represented as port numbers and match the given rule.The details-level parameter of the request determines whether they are displayed as UID's or objects.
	Others []interface{} `json:"others,omitempty" xml:"others"`
	// Range of TCP ports that match in the given rule.
	Tcp []ModelRange `json:"tcp,omitempty" xml:"tcp"`
	// Range of UDP ports that match in the given rule.
	Udp []ModelRange `json:"udp,omitempty" xml:"udp"`
}
