/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AddWithPosition struct {
	// Layer name or UID.
	Name string `json:"name" xml:"name"`
	// Layer position.
	Position int32 `json:"position" xml:"position"`
}
