/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Ike Phase 1 settings. Only applicable when the encryption-suite is set to [custom].
type IkeP1Request struct {
	// The hash algorithm to be used.
	DataIntegrity string `json:"data-integrity,omitempty" xml:"data-integrity"`
	// The Diffie-Hellman group to be used.
	DiffieHellmanGroup string `json:"diffie-hellman-group,omitempty" xml:"diffie-hellman-group"`
	// The encryption algorithm to be used.
	EncryptionAlgorithm string `json:"encryption-algorithm,omitempty" xml:"encryption-algorithm"`
}
