/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ScadaApplicationReply struct {
	// N/A
	AdditionalCategories []string `json:"additional-categories,omitempty" xml:"additional-categories"`
	// N/A
	ApplicationId int32 `json:"application-id,omitempty" xml:"application-id"`
	// Application signature generated by <a href=\"https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk103051\">Signature Tool</a>.
	ApplicationSignature string `json:"application-signature,omitempty" xml:"application-signature"`
	// SCADA application category.
	Category string `json:"category,omitempty" xml:"category"`
	// Color of the object. Should be one of existing colors.
	Color string `json:"color,omitempty" xml:"color"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	// N/A
	Description string `json:"description,omitempty" xml:"description"`
	Domain *ApiDomainIdentifier `json:"domain,omitempty" xml:"domain"`
	// How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	Groups []ApiObjectStandardIdentifier `json:"groups,omitempty" xml:"groups"`
	// Object icon.
	Icon string `json:"icon,omitempty" xml:"icon"`
	MetaInfo *MetaInfoForTopLevelReply `json:"meta-info,omitempty" xml:"meta-info"`
	// Object name. Should be unique in the domain.
	Name string `json:"name,omitempty" xml:"name"`
	// Indicates whether the object is read-only.
	ReadOnly bool `json:"read-only,omitempty" xml:"read-only"`
	// N/A
	Risk string `json:"risk,omitempty" xml:"risk"`
	// SCADA application properties.
	ScadaProperties []ScadaApplicationEntryItem `json:"scada-properties,omitempty" xml:"scada-properties"`
	// Collection of tag objects identified by the name or UID. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	Tags []ApiObjectStandardIdentifier `json:"tags,omitempty" xml:"tags"`
	// Type of the object.
	Type_ string `json:"type,omitempty" xml:"type"`
	// Object unique identifier.
	Uid string `json:"uid,omitempty" xml:"uid"`
	// True if this application site was defined by user (not predefined one).
	UserDefined bool `json:"user-defined,omitempty" xml:"user-defined"`
}
