/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Threat policy layers.
type MultiValueThreatLayer struct {
	// Collection of Threat layer objects to be added identified by the name or UID.
	Add []AddWithPosition `json:"add,omitempty" xml:"add"`
	// Collection of Threat layer objects to be removed identified by the name or UID.
	Remove []string `json:"remove,omitempty" xml:"remove"`
	// Collection of Threat layer objects to be set identified by the name or UID. Replaces existing Threat layers.
	Value []string `json:"value,omitempty" xml:"value"`
}
