/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Login message.
type LoginMessageReply struct {
	Domain *ApiDomainIdentifier `json:"domain,omitempty" xml:"domain"`
	// Login message header.
	Header string `json:"header,omitempty" xml:"header"`
	// Login message body.
	Message string `json:"message,omitempty" xml:"message"`
	// Whether to show login message.
	ShowMessage bool `json:"show-message,omitempty" xml:"show-message"`
	// Type of the object.
	Type_ string `json:"type,omitempty" xml:"type"`
	// Add warning sign.
	Warning bool `json:"warning,omitempty" xml:"warning"`
}
