/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LoginMessageRequestSet struct {
	// The level of detail for some of the fields in the response can vary from showing only the UID value of the object to a fully detailed representation of the object.
	DetailsLevel string `json:"details-level,omitempty" xml:"details-level"`
	// Login message header.
	Header string `json:"header,omitempty" xml:"header"`
	// Login message body.
	Message string `json:"message,omitempty" xml:"message"`
	// Whether to show login message.
	ShowMessage bool `json:"show-message,omitempty" xml:"show-message"`
	// Add warning sign.
	Warning bool `json:"warning,omitempty" xml:"warning"`
}
