/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DataCenterContentObjectReply struct {
	// Additional properties on the object.
	AdditionalProperties []DataCenterObjectProperty `json:"additional-properties,omitempty" xml:"additional-properties"`
	DataCenterObject *ApiObjectStandardIdentifier `json:"data-center-object,omitempty" xml:"data-center-object"`
	// Object management name.
	Name string `json:"name,omitempty" xml:"name"`
	// Object name in the Data Center.
	NameInDataCenter string `json:"name-in-data-center,omitempty" xml:"name-in-data-center"`
	// Object type in Data Center.
	TypeInDataCenter string `json:"type-in-data-center,omitempty" xml:"type-in-data-center"`
	// Unique identifier of the object in the Data Center.
	UidInDataCenter string `json:"uid-in-data-center,omitempty" xml:"uid-in-data-center"`
}
