/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AllActivationsByProtectionReply struct {
	Default_ *ActivationReply `json:"default,omitempty" xml:"default"`
	Final *ActivationReply `json:"final,omitempty" xml:"final"`
	Override *ActivationReply `json:"override,omitempty" xml:"override"`
	// IPS protection name.
	Protection string `json:"protection,omitempty" xml:"protection"`
	// IPS protection unique identifier.
	ProtectionUid string `json:"protection-uid,omitempty" xml:"protection-uid"`
}
