/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// N/A
type IpsAdditionalPropertiesReply struct {
	// Object name. Should be unique in the domain.
	Name string `json:"name,omitempty" xml:"name"`
	// Object unique identifier.
	Uid string `json:"uid,omitempty" xml:"uid"`
	// N/A
	Values []ObjIdNamePair `json:"values,omitempty" xml:"values"`
}
