/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiQueryOrderRequest struct {
	// Sorts results by the given field in ascending order.
	ASC string `json:"ASC,omitempty" xml:"ASC"`
	// Sorts results by the given field in descending order.
	DESC string `json:"DESC,omitempty" xml:"DESC"`
}
