/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Custom fields.
type CustomSummaryFieldsRequest struct {
	// First custom field.
	Field1 string `json:"field-1,omitempty" xml:"field-1"`
	// Second custom field.
	Field2 string `json:"field-2,omitempty" xml:"field-2"`
	// Third custom field.
	Field3 string `json:"field-3,omitempty" xml:"field-3"`
}
