/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PutFileRequest struct {
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	// N/A
	FileContent string `json:"file-content,omitempty" xml:"file-content"`
	// N/A
	FileName string `json:"file-name,omitempty" xml:"file-name"`
	// N/A
	FilePath string `json:"file-path,omitempty" xml:"file-path"`
	// On what targets to execute this command. Targets may be identified by their name, or object unique identifier.
	Targets string `json:"targets" xml:"targets"`
}
