/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NetworkInterfaceRequestEdit struct {
	// N/A
	AntiSpoofing bool `json:"anti-spoofing,omitempty" xml:"anti-spoofing"`
	AntiSpoofingSettings *AntiSpoofingSettingsRequest `json:"anti-spoofing-settings,omitempty" xml:"anti-spoofing-settings"`
	// Color of the object. Should be one of existing colors.
	Color string `json:"color,omitempty" xml:"color"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	// The level of detail for some of the fields in the response can vary from showing only the UID value of the object to a fully detailed representation of the object.
	DetailsLevel string `json:"details-level,omitempty" xml:"details-level"`
	// Apply changes ignoring errors. You won't be able to publish such a changes. If ignore-warnings flag was omitted - warnings will also be ignored.
	IgnoreErrors bool `json:"ignore-errors,omitempty" xml:"ignore-errors"`
	// Apply changes ignoring warnings.
	IgnoreWarnings bool `json:"ignore-warnings,omitempty" xml:"ignore-warnings"`
	// IPv4 or IPv6 address. If both addresses are required use ipv4-address and ipv6-address fields explicitly.
	IpAddress string `json:"ip-address,omitempty" xml:"ip-address"`
	// IPv4 address.
	Ipv4Address string `json:"ipv4-address,omitempty" xml:"ipv4-address"`
	// IPv4 network mask length.
	Ipv4MaskLength string `json:"ipv4-mask-length,omitempty" xml:"ipv4-mask-length"`
	// IPv4 network address.
	Ipv4NetworkMask string `json:"ipv4-network-mask,omitempty" xml:"ipv4-network-mask"`
	// IPv6 address.
	Ipv6Address string `json:"ipv6-address,omitempty" xml:"ipv6-address"`
	// IPv6 network mask length.
	Ipv6MaskLength string `json:"ipv6-mask-length,omitempty" xml:"ipv6-mask-length"`
	// IPv6 network address.
	Ipv6NetworkMask string `json:"ipv6-network-mask,omitempty" xml:"ipv6-network-mask"`
	// IPv4 or IPv6 network mask length.
	MaskLength string `json:"mask-length,omitempty" xml:"mask-length"`
	// Object name.
	Name string `json:"name,omitempty" xml:"name"`
	// IPv4 or IPv6 network mask. If both masks are required use ipv4-network-mask and ipv6-network-mask fields explicitly. Instead of providing mask itself it is possible to specify IPv4 or IPv6 mask length in mask-length field. If both masks length are required use ipv4-mask-length and  ipv6-mask-length fields explicitly.
	NetworkMask string `json:"network-mask,omitempty" xml:"network-mask"`
	// New name of the object.
	NewName string `json:"new-name,omitempty" xml:"new-name"`
	// N/A
	SecurityZone bool `json:"security-zone,omitempty" xml:"security-zone"`
	SecurityZoneSettings *SecurityZoneSettingsRequest `json:"security-zone-settings,omitempty" xml:"security-zone-settings"`
	// Collection of tag identifiers.
	Tags *interface{} `json:"tags,omitempty" xml:"tags"`
	// N/A
	Topology string `json:"topology,omitempty" xml:"topology"`
	TopologySettings *InternalTopologySettingsRequest `json:"topology-settings,omitempty" xml:"topology-settings"`
	// Object unique identifier.
	Uid string `json:"uid" xml:"uid"`
}
