/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GatewayServerPolicyReplyClusterMemberReply struct {
	// Cluster member name.
	Name string `json:"name,omitempty" xml:"name"`
	// The name of the installed policy.
	PolicyName string `json:"policy-name,omitempty" xml:"policy-name"`
	Revision *ApiObjectStandardIdentifier `json:"revision,omitempty" xml:"revision"`
	// Cluster member unique identifier.
	Uid string `json:"uid,omitempty" xml:"uid"`
}
