/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TrustedClientReply struct {
	// Color of the object. Should be one of existing colors.
	Color string `json:"color,omitempty" xml:"color"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	Domain *ApiDomainIdentifier `json:"domain,omitempty" xml:"domain"`
	// Domains assignment. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	DomainsAssignment []ApiObjectStandardIdentifier `json:"domains-assignment,omitempty" xml:"domains-assignment"`
	// Object icon.
	Icon string `json:"icon,omitempty" xml:"icon"`
	// IPv4 address.
	Ipv4Address string `json:"ipv4-address,omitempty" xml:"ipv4-address"`
	// First IPv4 address in the range.
	Ipv4AddressFirst string `json:"ipv4-address-first,omitempty" xml:"ipv4-address-first"`
	// Last IPv4 address in the range.
	Ipv4AddressLast string `json:"ipv4-address-last,omitempty" xml:"ipv4-address-last"`
	// IPv6 address.
	Ipv6Address string `json:"ipv6-address,omitempty" xml:"ipv6-address"`
	// First IPv6 address in the range.
	Ipv6AddressFirst string `json:"ipv6-address-first,omitempty" xml:"ipv6-address-first"`
	// Last IPv6 address in the range.
	Ipv6AddressLast string `json:"ipv6-address-last,omitempty" xml:"ipv6-address-last"`
	// IPv4 mask length.
	MaskLength4 int32 `json:"mask-length4,omitempty" xml:"mask-length4"`
	// IPv6 mask length.
	MaskLength6 int32 `json:"mask-length6,omitempty" xml:"mask-length6"`
	MetaInfo *MetaInfoForTopLevelReply `json:"meta-info,omitempty" xml:"meta-info"`
	// Let this trusted client connect to all Multi-Domain Servers in the deployment.
	MultiDomainServerTrustedClient bool `json:"multi-domain-server-trusted-client,omitempty" xml:"multi-domain-server-trusted-client"`
	// Object name. Should be unique in the domain.
	Name string `json:"name,omitempty" xml:"name"`
	// Indicates whether the object is read-only.
	ReadOnly bool `json:"read-only,omitempty" xml:"read-only"`
	// IPv4 mask.
	SubnetMask4 string `json:"subnet-mask4,omitempty" xml:"subnet-mask4"`
	// Collection of tag objects identified by the name or UID. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	Tags []ApiObjectStandardIdentifier `json:"tags,omitempty" xml:"tags"`
	// Trusted client type.
	Type_ string `json:"type,omitempty" xml:"type"`
	// Object unique identifier.
	Uid string `json:"uid,omitempty" xml:"uid"`
	// IP wild card (e.g. 192.0.2.*).
	WildCard string `json:"wild-card,omitempty" xml:"wild-card"`
}
