/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NatRuleReply struct {
	// N/A
	AutoGenerated bool `json:"auto-generated,omitempty" xml:"auto-generated"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	Domain *ApiDomainIdentifier `json:"domain,omitempty" xml:"domain"`
	// Enable/Disable the rule.
	Enabled bool `json:"enabled,omitempty" xml:"enabled"`
	// Which gateway, identified by the name or UID, to install the policy. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	InstallOn []ApiObjectStandardIdentifier `json:"install-on,omitempty" xml:"install-on"`
	MetaInfo *MetaInfoForTopLevelReply `json:"meta-info,omitempty" xml:"meta-info"`
	// Nat method.
	Method string `json:"method,omitempty" xml:"method"`
	OriginalDestination *ApiObjectStandardIdentifier `json:"original-destination,omitempty" xml:"original-destination"`
	OriginalService *ApiObjectStandardIdentifier `json:"original-service,omitempty" xml:"original-service"`
	OriginalSource *ApiObjectStandardIdentifier `json:"original-source,omitempty" xml:"original-source"`
	// N/A
	Package_ string `json:"package,omitempty" xml:"package"`
	TranslatedDestination *ApiObjectStandardIdentifier `json:"translated-destination,omitempty" xml:"translated-destination"`
	TranslatedService *ApiObjectStandardIdentifier `json:"translated-service,omitempty" xml:"translated-service"`
	TranslatedSource *ApiObjectStandardIdentifier `json:"translated-source,omitempty" xml:"translated-source"`
	// Type of the object.
	Type_ string `json:"type,omitempty" xml:"type"`
	// Object unique identifier.
	Uid string `json:"uid,omitempty" xml:"uid"`
}
