/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RunScriptRequest struct {
	// Script arguments.
	Args string `json:"args,omitempty" xml:"args"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	// Script body.
	Script string `json:"script" xml:"script"`
	// Script name.
	ScriptName string `json:"script-name" xml:"script-name"`
	// On what targets to execute this command. Targets may be identified by their name, or object unique identifier.
	Targets string `json:"targets" xml:"targets"`
}
