/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// N/A
type RemoteUpdatableObjectMetaData struct {
	UpdatedOnUpdatableObjectsRepository *DateReply `json:"updated-on-updatable-objects-repository,omitempty" xml:"updated-on-updatable-objects-repository"`
}
