/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PolicyInstallationRequest struct {
	// Set to be true in order to install the Access Control policy. By default, the value is true if Access Control policy is enabled on the input policy package, otherwise false.
	Access bool `json:"access,omitempty" xml:"access"`
	// Set to be true in order to install the Desktop Security policy. By default, the value is true if desktop security policy is enabled on the input policy package, otherwise false.
	DesktopSecurity bool `json:"desktop-security,omitempty" xml:"desktop-security"`
	// Relevant for the gateway clusters. If true, the policy is installed on all the cluster members. If the installation on a cluster member fails, don't install on that cluster.
	InstallOnAllClusterMembersOrFail bool `json:"install-on-all-cluster-members-or-fail,omitempty" xml:"install-on-all-cluster-members-or-fail"`
	// The name of the Policy Package to be installed.
	PolicyPackage string `json:"policy-package" xml:"policy-package"`
	// If true, prepares the policy for the installation, but doesn't install it on an installation target.
	PrepareOnly bool `json:"prepare-only,omitempty" xml:"prepare-only"`
	// Set to be true in order to install the QoS policy. By default, the value is true if Quality-of-Service policy is enabled on the input policy package, otherwise false.
	Qos bool `json:"qos,omitempty" xml:"qos"`
	// The UID of the revision of the policy to install.
	Revision string `json:"revision,omitempty" xml:"revision"`
	// On what targets to execute this command. Targets may be identified by their name, or object unique identifier.
	Targets string `json:"targets" xml:"targets"`
	// Set to be true in order to install the Threat Prevention policy. By default, the value is true if Threat Prevention policy is enabled on the input policy package, otherwise false.
	ThreatPrevention bool `json:"threat-prevention,omitempty" xml:"threat-prevention"`
}
