/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Return results matching the specified filter.
type UpdatableObjectsRepositoryContentObjectFilter struct {
	// Return results under the specified Updatable Object.
	ParentUidInUpdatableObjectsRepository string `json:"parent-uid-in-updatable-objects-repository,omitempty" xml:"parent-uid-in-updatable-objects-repository"`
	// Return results containing the specified text value.
	Text string `json:"text,omitempty" xml:"text"`
	// Return results under the specified uri value.
	Uri string `json:"uri,omitempty" xml:"uri"`
}
