/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WebApiExportRequest struct {
	// N/A
	ExcludeClasses []string `json:"exclude-classes,omitempty" xml:"exclude-classes"`
	// N/A
	ExcludeTopics []string `json:"exclude-topics,omitempty" xml:"exclude-topics"`
	// N/A
	ExportFilesByClass bool `json:"export-files-by-class,omitempty" xml:"export-files-by-class"`
	// N/A
	IncludeClasses []string `json:"include-classes,omitempty" xml:"include-classes"`
	// N/A
	IncludeTopics []string `json:"include-topics,omitempty" xml:"include-topics"`
	// N/A
	QueryLimit int32 `json:"query-limit,omitempty" xml:"query-limit"`
}
