/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HourRange struct {
	// Is hour range enabled.
	Enabled bool `json:"enabled,omitempty" xml:"enabled"`
	// Time in format HH:MM.
	From string `json:"from,omitempty" xml:"from"`
	// Hour range index.
	Index int32 `json:"index,omitempty" xml:"index"`
	// Time in format HH:MM.
	To string `json:"to,omitempty" xml:"to"`
}
