/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VpnMeshedCommunityRequestNew struct {
	// Color of the object. Should be one of existing colors.
	Color string `json:"color,omitempty" xml:"color"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	// The level of detail for some of the fields in the response can vary from showing only the UID value of the object to a fully detailed representation of the object.
	DetailsLevel string `json:"details-level,omitempty" xml:"details-level"`
	// The encryption method to be used.
	EncryptionMethod string `json:"encryption-method,omitempty" xml:"encryption-method"`
	// The encryption suite to be used.
	EncryptionSuite string `json:"encryption-suite,omitempty" xml:"encryption-suite"`
	// Collection of Gateway objects identified by the name or UID.
	Gateways string `json:"gateways,omitempty" xml:"gateways"`
	// Apply changes ignoring errors. You won't be able to publish such a changes. If ignore-warnings flag was omitted - warnings will also be ignored.
	IgnoreErrors bool `json:"ignore-errors,omitempty" xml:"ignore-errors"`
	// Apply changes ignoring warnings.
	IgnoreWarnings bool `json:"ignore-warnings,omitempty" xml:"ignore-warnings"`
	IkePhase1 *IkeP1Request `json:"ike-phase-1,omitempty" xml:"ike-phase-1"`
	IkePhase2 *IkeP2Request `json:"ike-phase-2,omitempty" xml:"ike-phase-2"`
	// Object name. Should be unique in the domain.
	Name string `json:"name" xml:"name"`
	SharedSecrets *SharedSecretRequest `json:"shared-secrets,omitempty" xml:"shared-secrets"`
	// Collection of tag identifiers.
	Tags string `json:"tags,omitempty" xml:"tags"`
	// Indicates whether the shared secret should be used for all external gateways.
	UseSharedSecret bool `json:"use-shared-secret,omitempty" xml:"use-shared-secret"`
}
