/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Used to setup the CPMI client entity.
type CpmiRequest struct {
	// A profile to set the log reading permissions by for the client entity.
	AdministratorProfile string `json:"administrator-profile,omitempty" xml:"administrator-profile"`
	// Whether to enable this client entity on the Opsec Application.
	Enabled bool `json:"enabled,omitempty" xml:"enabled"`
	// Whether to use the Admin's credentials to login to the security management server.
	UseAdministratorCredentials bool `json:"use-administrator-credentials,omitempty" xml:"use-administrator-credentials"`
}
