/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TcpServiceRequestEdit struct {
	AggressiveAging *AggressiveAgingRequest `json:"aggressive-aging,omitempty" xml:"aggressive-aging"`
	// Color of the object. Should be one of existing colors.
	Color string `json:"color,omitempty" xml:"color"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	// The level of detail for some of the fields in the response can vary from showing only the UID value of the object to a fully detailed representation of the object.
	DetailsLevel string `json:"details-level,omitempty" xml:"details-level"`
	Groups *Add `json:"groups,omitempty" xml:"groups"`
	// Apply changes ignoring errors. You won't be able to publish such a changes. If ignore-warnings flag was omitted - warnings will also be ignored.
	IgnoreErrors bool `json:"ignore-errors,omitempty" xml:"ignore-errors"`
	// Apply changes ignoring warnings.
	IgnoreWarnings bool `json:"ignore-warnings,omitempty" xml:"ignore-warnings"`
	// Keep connections open after policy has been installed even if they are not allowed under the new policy. This overrides the settings in the Connection Persistence page. If you change this property, the change will not affect open connections, but only future connections.
	KeepConnectionsOpenAfterPolicyInstallation bool `json:"keep-connections-open-after-policy-installation,omitempty" xml:"keep-connections-open-after-policy-installation"`
	// A value of true enables matching by the selected protocol's signature - the signature identifies the protocol as genuine. Select this option to limit the port to the specified protocol. If the selected protocol does not support matching by signature, this field cannot be set to true.
	MatchByProtocolSignature bool `json:"match-by-protocol-signature,omitempty" xml:"match-by-protocol-signature"`
	// Indicates whether this service is used when 'Any' is set as the rule's service and there are several service objects with the same source port and protocol.
	MatchForAny bool `json:"match-for-any,omitempty" xml:"match-for-any"`
	// Object name.
	Name string `json:"name,omitempty" xml:"name"`
	// New name of the object.
	NewName string `json:"new-name,omitempty" xml:"new-name"`
	// Indicates whether this service is a Data Domain service which has been overridden.
	OverrideDefaultSettings bool `json:"override-default-settings,omitempty" xml:"override-default-settings"`
	// The number of the port used to provide this service. To specify a port range, place a hyphen between the lowest and highest port numbers, for example 44-55.
	Port string `json:"port,omitempty" xml:"port"`
	// Select the protocol type associated with the service, and by implication, the management server (if any) that enforces Content Security and Authentication for the service. Selecting a Protocol Type invokes the specific protocol handlers for each protocol type, thus enabling higher level of security by parsing the protocol, and higher level of connectivity by tracking dynamic actions (such as opening of ports).
	Protocol string `json:"protocol,omitempty" xml:"protocol"`
	// Time (in seconds) before the session times out.
	SessionTimeout int32 `json:"session-timeout,omitempty" xml:"session-timeout"`
	// Port number for the client side service. If specified, only those Source port Numbers will be Accepted, Dropped, or Rejected during packet inspection. Otherwise, the source port is not inspected.
	SourcePort string `json:"source-port,omitempty" xml:"source-port"`
	// Enables state-synchronized High Availability or Load Sharing on a ClusterXL or OPSEC-certified cluster.
	SyncConnectionsOnCluster bool `json:"sync-connections-on-cluster,omitempty" xml:"sync-connections-on-cluster"`
	Tags *Add `json:"tags,omitempty" xml:"tags"`
	// Object unique identifier.
	Uid string `json:"uid" xml:"uid"`
	// Use default virtual session timeout.
	UseDefaultSessionTimeout bool `json:"use-default-session-timeout,omitempty" xml:"use-default-session-timeout"`
}
