/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// IPS blade settings.
type IpsSettingsRequest struct {
	// Whether to exclude protections depending on their level of performance impact.
	ExcludeProtectionWithPerformanceImpact bool `json:"exclude-protection-with-performance-impact,omitempty" xml:"exclude-protection-with-performance-impact"`
	// Exclude protections with this level of performance impact.
	ExcludeProtectionWithPerformanceImpactMode string `json:"exclude-protection-with-performance-impact-mode,omitempty" xml:"exclude-protection-with-performance-impact-mode"`
	// Whether to exclude protections depending on their level of severity.
	ExcludeProtectionWithSeverity bool `json:"exclude-protection-with-severity,omitempty" xml:"exclude-protection-with-severity"`
	// Exclude protections with this level of severity.
	ExcludeProtectionWithSeverityMode string `json:"exclude-protection-with-severity-mode,omitempty" xml:"exclude-protection-with-severity-mode"`
	// Activation of newly updated protections.
	NewlyUpdatedProtections string `json:"newly-updated-protections,omitempty" xml:"newly-updated-protections"`
}
