/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// N/A
type AntiSpoofingSettingsReply struct {
	// If packets will be rejected (the Prevent option) or whether the packets will be monitored (the Detect option).
	Action string `json:"action,omitempty" xml:"action"`
}
