/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Information about the domain the object belongs to.
type ApiDomainIdentifier struct {
	// Domain type.
	DomainType string `json:"domain-type,omitempty" xml:"domain-type"`
	// Object name. Should be unique in the domain.
	Name string `json:"name,omitempty" xml:"name"`
	// Object unique identifier.
	Uid string `json:"uid,omitempty" xml:"uid"`
}
