/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Sets filter preferences.
type ApiRulebaseFilterSettingsRequest struct {
	PacketSearchSettings *ApiRulebaseFilterSettingsRequestPacketSearchSettings `json:"packet-search-settings,omitempty" xml:"packet-search-settings"`
	// When set to 'general', both the Full Text Search and Packet Search are enabled. In this mode, Packet Search will not match on 'Any' object, a negated cell or a group-with-exclusion. When the search-mode is set to 'packet', by default, the match on 'Any' object, a negated cell or a group-with-exclusion are enabled. packet-search-settings may be provided to change the default behavior.
	SearchMode string `json:"search-mode,omitempty" xml:"search-mode"`
}
