/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CdmCommandReply struct {
	// Asynchronous task unique identifiers.
	Tasks []string `json:"tasks,omitempty" xml:"tasks"`
}
