/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VerifyPolicyRequest struct {
	// Policy package identified by the name or UID.
	PolicyPackage string `json:"policy-package" xml:"policy-package"`
}
