/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The threat rules to apply this group on in the case of apply-on manually-select-threat-rules.
type ManualAttachment struct {
	// The layer of the threat rule to which the group is to be attached.
	Layer string `json:"layer" xml:"layer"`
	// The name of the threat rule to which the group is to be attached.
	Name string `json:"name,omitempty" xml:"name"`
	// Position in the rulebase.
	Position int32 `json:"position,omitempty" xml:"position"`
	// The rule-number of the threat rule to which the group is to be attached.
	RuleNumber string `json:"rule-number,omitempty" xml:"rule-number"`
	// The uid of the threat rule to which the group is to be attached.
	Uid string `json:"uid" xml:"uid"`
}
