/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Settings overrides.
type ActivationReply struct {
	// Protection action.
	Action string `json:"action,omitempty" xml:"action"`
	// Capture packets.
	CapturePackets bool `json:"capture-packets,omitempty" xml:"capture-packets"`
	// Tracking method for protection.
	Track string `json:"track,omitempty" xml:"track"`
}
