/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// NAT settings.
type NatSettingsRequest struct {
	// Whether to add automatic address translation rules.
	AutoRule bool `json:"auto-rule" xml:"auto-rule"`
	// Hide behind method. This parameter is not required in case \"method\" parameter is \"static\".
	HideBehind string `json:"hide-behind,omitempty" xml:"hide-behind"`
	// Which gateway should apply the NAT translation.
	InstallOn string `json:"install-on,omitempty" xml:"install-on"`
	// IPv4 or IPv6 address. If both addresses are required use ipv4-address and ipv6-address fields explicitly. This parameter is not required in case \"method\" parameter is \"hide\" and \"hide-behind\" parameter is \"gateway\".
	IpAddress string `json:"ip-address" xml:"ip-address"`
	// IPv4 address.
	Ipv4Address string `json:"ipv4-address,omitempty" xml:"ipv4-address"`
	// IPv6 address.
	Ipv6Address string `json:"ipv6-address,omitempty" xml:"ipv6-address"`
	// NAT translation method.
	Method string `json:"method,omitempty" xml:"method"`
}
