/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GlobalAssignmentWithDependentReply struct {
	// N/A
	AssignmentStatus string `json:"assignment-status,omitempty" xml:"assignment-status"`
	AssignmentUpToDate *ApiDateReply `json:"assignment-up-to-date,omitempty" xml:"assignment-up-to-date"`
	// Color of the object. Should be one of existing colors.
	Color string `json:"color,omitempty" xml:"color"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	DependentDomain *ApiObjectStandardIdentifier `json:"dependent-domain,omitempty" xml:"dependent-domain"`
	Domain *ApiDomainIdentifier `json:"domain,omitempty" xml:"domain"`
	// Global domain access policy that is assigned to a dependent domain.
	GlobalAccessPolicy string `json:"global-access-policy,omitempty" xml:"global-access-policy"`
	// Global domain threat prevention policy that is assigned to a dependent domain.
	GlobalThreatPreventionPolicy string `json:"global-threat-prevention-policy,omitempty" xml:"global-threat-prevention-policy"`
	// Object icon.
	Icon string `json:"icon,omitempty" xml:"icon"`
	// N/A
	ManageProtectionActions bool `json:"manage-protection-actions,omitempty" xml:"manage-protection-actions"`
	MetaInfo *MetaInfoForTopLevelReply `json:"meta-info,omitempty" xml:"meta-info"`
	// Object name. Should be unique in the domain.
	Name string `json:"name,omitempty" xml:"name"`
	// Indicates whether the object is read-only.
	ReadOnly bool `json:"read-only,omitempty" xml:"read-only"`
	// Collection of tag objects identified by the name or UID. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	Tags []ApiObjectStandardIdentifier `json:"tags,omitempty" xml:"tags"`
	// Type of the object.
	Type_ string `json:"type,omitempty" xml:"type"`
	// Object unique identifier.
	Uid string `json:"uid,omitempty" xml:"uid"`
}
