/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PolicyInstallationReply struct {
	// Asynchronous task unique identifier.
	TaskId string `json:"task-id,omitempty" xml:"task-id"`
}
