/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccessRuleIdentifierRequestShow struct {
	// The level of detail for some of the fields in the response can vary from showing only the UID value of the object to a fully detailed representation of the object.
	DetailsLevel string `json:"details-level,omitempty" xml:"details-level"`
	HitsSettings *HitsSettingsRequest `json:"hits-settings,omitempty" xml:"hits-settings"`
	// Layer that the rule belongs to identified by the name or UID.
	Layer string `json:"layer" xml:"layer"`
	// Object name.
	Name string `json:"name,omitempty" xml:"name"`
	// Rule number.
	RuleNumber int32 `json:"rule-number,omitempty" xml:"rule-number"`
	// When true, the source, destination and services & applications parameters are displayed as ranges of IP addresses and port numbers rather than network objects.<br /> Objects that are not represented using IP addresses or port numbers are presented as objects.<br /> In addition, the response of each rule does not contain the parameters: source, source-negate, destination, destination-negate, service and service-negate, but instead it contains the parameters: source-ranges, destination-ranges and service-ranges.<br /><br /> Note: Requesting to show rules as ranges is limited up to 20 rules per request, otherwise an error is returned. If you wish to request more rules, use the offset and limit parameters to limit your request.
	ShowAsRanges bool `json:"show-as-ranges,omitempty" xml:"show-as-ranges"`
	// N/A
	ShowHits bool `json:"show-hits,omitempty" xml:"show-hits"`
	// Object unique identifier.
	Uid string `json:"uid" xml:"uid"`
}
