/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WorkSessionAssignRequest struct {
	// Assignee administrator name. Specify it to assign a session to another administrator.
	AdministratorName string `json:"administrator-name,omitempty" xml:"administrator-name"`
	// Allows assignment of an active session, currently executed by another administrator.
	DisconnectActiveSession bool `json:"disconnect-active-session,omitempty" xml:"disconnect-active-session"`
	// Session unique identifier. Specify it to assign a different session than the one you currently use.
	Uid string `json:"uid,omitempty" xml:"uid"`
}
