/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QueryAccessRulebaseRequest struct {
	// Indicates whether to dereference \"members\" field by details level for every object in reply.
	DereferenceGroupMembers bool `json:"dereference-group-members,omitempty" xml:"dereference-group-members"`
	// The level of detail for some of the fields in the response can vary from showing only the UID value of the object to a fully detailed representation of the object.
	DetailsLevel string `json:"details-level,omitempty" xml:"details-level"`
	// Search expression to filter the rulebase. The provided text should be exactly the same as it would be given in Smart Console. The logical operators in the expression ('AND', 'OR') should be provided in capital letters. If an operator is not used, the default OR operator applies.
	Filter string `json:"filter,omitempty" xml:"filter"`
	FilterSettings *ApiRulebaseFilterSettingsRequest `json:"filter-settings,omitempty" xml:"filter-settings"`
	HitsSettings *HitsSettingsRequest `json:"hits-settings,omitempty" xml:"hits-settings"`
	// No more than that many results will be returned.
	Limit int32 `json:"limit,omitempty" xml:"limit"`
	// Object name. Should be unique in the domain.
	Name string `json:"name" xml:"name"`
	// Skip that many results before beginning to return them.
	Offset int32 `json:"offset,omitempty" xml:"offset"`
	// Sorts results by the given field. By default the results are sorted in the ascending order by name.
	Order []ApiQueryOrderRequest `json:"order,omitempty" xml:"order"`
	// Name of the package.
	Package_ string `json:"package,omitempty" xml:"package"`
	// When true, the source, destination and services & applications parameters are displayed as ranges of IP addresses and port numbers rather than network objects.<br /> Objects that are not represented using IP addresses or port numbers are presented as objects.<br /> In addition, the response of each rule does not contain the parameters: source, source-negate, destination, destination-negate, service and service-negate, but instead it contains the parameters: source-ranges, destination-ranges and service-ranges.<br /><br /> Note: Requesting to show rules as ranges is limited up to 20 rules per request, otherwise an error is returned. If you wish to request more rules, use the offset and limit parameters to limit your request.
	ShowAsRanges bool `json:"show-as-ranges,omitempty" xml:"show-as-ranges"`
	// N/A
	ShowHits bool `json:"show-hits,omitempty" xml:"show-hits"`
	// Indicates whether to calculate and show \"groups\" field for every object in reply.
	ShowMembership bool `json:"show-membership,omitempty" xml:"show-membership"`
	// Object unique identifier.
	Uid string `json:"uid,omitempty" xml:"uid"`
	// N/A
	UseObjectDictionary bool `json:"use-object-dictionary,omitempty" xml:"use-object-dictionary"`
}
