/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TaskQueryRequest struct {
	// The level of detail for some of the fields in the response can vary from showing only the UID value of the object to a fully detailed representation of the object.
	DetailsLevel string `json:"details-level,omitempty" xml:"details-level"`
	// The date from which tracking tasks is to be performed, by the task's last update date. ISO 8601. If timezone isn't specified in the input, the Management server's timezone is used.
	FromDate string `json:"from-date,omitempty" xml:"from-date"`
	// Initiator's name. If name isn't specified, tasks from all initiators will be shown.
	Initiator string `json:"initiator,omitempty" xml:"initiator"`
	// No more than that many results will be returned.
	Limit int32 `json:"limit,omitempty" xml:"limit"`
	// Skip that many results before beginning to return them.
	Offset int32 `json:"offset,omitempty" xml:"offset"`
	// Sorts results by the given field. By default the results are sorted in the descending order by the task's last update date.
	Order []ApiQueryOrderRequest `json:"order,omitempty" xml:"order"`
	// Status.
	Status string `json:"status,omitempty" xml:"status"`
	// The date until which tracking tasks is to be performed, by the task's last update date. ISO 8601. If timezone isn't specified in the input, the Management server's timezone is used.
	ToDate string `json:"to-date,omitempty" xml:"to-date"`
}
