/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Displays the group's matched content as ranges of IP addresses, in case 'show-as-ranges' is set to true.<br />In this case, the 'members' parameter is omitted.
type IpRanges struct {
	// Objects which are not represented as IP addresses and are negated in the given rule - for example if negate is set for the source or destination of this rule, or if they appear in the 'exclude' member of a group-with-exclusion object. The details-level parameter of the request determines whether they are displayed as UID's or objects.
	ExcludedOthers []interface{} `json:"excluded-others,omitempty" xml:"excluded-others"`
	// Range of IPv4 addresses that match in the given rule.
	Ipv4 []ModelRange `json:"ipv4,omitempty" xml:"ipv4"`
	// Range of IPv6 addresses that match in the given rule.
	Ipv6 []ModelRange `json:"ipv6,omitempty" xml:"ipv6"`
	// Objects which are not represented as IP addresses and match the given rule. The details-level parameter of the request determines whether they are displayed as UID's or objects.
	Others []interface{} `json:"others,omitempty" xml:"others"`
}
