/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MultiCastAddressRangeStandardReply struct {
	Domain *ApiDomainIdentifier `json:"domain,omitempty" xml:"domain"`
	// First IPv4 address in the range.
	Ipv4AddressFirst string `json:"ipv4-address-first,omitempty" xml:"ipv4-address-first"`
	// Last IPv4 address in the range.
	Ipv4AddressLast string `json:"ipv4-address-last,omitempty" xml:"ipv4-address-last"`
	// First IPv6 address in the range.
	Ipv6AddressFirst string `json:"ipv6-address-first,omitempty" xml:"ipv6-address-first"`
	// Last IPv6 address in the range.
	Ipv6AddressLast string `json:"ipv6-address-last,omitempty" xml:"ipv6-address-last"`
	// Object name. Should be unique in the domain.
	Name string `json:"name,omitempty" xml:"name"`
	// Type of the object.
	Type_ string `json:"type,omitempty" xml:"type"`
	// Object unique identifier.
	Uid string `json:"uid,omitempty" xml:"uid"`
}
