/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WorkSessionReply struct {
	// The name of the application serving the web_api requests.
	Application string `json:"application,omitempty" xml:"application"`
	// Number of pending changes.
	Changes int32 `json:"changes,omitempty" xml:"changes"`
	// Color of the object. Should be one of existing colors.
	Color string `json:"color,omitempty" xml:"color"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	// N/A
	ConnectionMode string `json:"connection-mode,omitempty" xml:"connection-mode"`
	// Session description.
	Description string `json:"description,omitempty" xml:"description"`
	Domain *ApiDomainIdentifier `json:"domain,omitempty" xml:"domain"`
	// Administrator email.
	Email string `json:"email,omitempty" xml:"email"`
	// True if the session is expired.
	ExpiredSession bool `json:"expired-session,omitempty" xml:"expired-session"`
	// Object icon.
	Icon string `json:"icon,omitempty" xml:"icon"`
	// True if the session is in work state.
	InWork bool `json:"in-work,omitempty" xml:"in-work"`
	// IP address from which the session was initiated.
	IpAddress string `json:"ip-address,omitempty" xml:"ip-address"`
	LastLoginTime *ApiDateReply `json:"last-login-time,omitempty" xml:"last-login-time"`
	LastLogoutTime *ApiDateReply `json:"last-logout-time,omitempty" xml:"last-logout-time"`
	// Number of locked objects.
	Locks int32 `json:"locks,omitempty" xml:"locks"`
	MetaInfo *MetaInfoForTopLevelReply `json:"meta-info,omitempty" xml:"meta-info"`
	// Object name. Should be unique in the domain.
	Name string `json:"name,omitempty" xml:"name"`
	// Administrator phone number.
	PhoneNumber string `json:"phone-number,omitempty" xml:"phone-number"`
	PublishTime *ApiDateReply `json:"publish-time,omitempty" xml:"publish-time"`
	// Indicates whether the object is read-only.
	ReadOnly bool `json:"read-only,omitempty" xml:"read-only"`
	// Session expiration timeout in seconds.
	SessionTimeout int32 `json:"session-timeout,omitempty" xml:"session-timeout"`
	// Session state.
	State string `json:"state,omitempty" xml:"state"`
	// Collection of tag objects identified by the name or UID. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	Tags []ApiObjectStandardIdentifier `json:"tags,omitempty" xml:"tags"`
	// Type of the object.
	Type_ string `json:"type,omitempty" xml:"type"`
	// Object unique identifier.
	Uid string `json:"uid,omitempty" xml:"uid"`
	// The name of the logged in user.
	UserName string `json:"user-name,omitempty" xml:"user-name"`
}
