/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ThreatRuleReply struct {
	Action *ApiObjectStandardIdentifier `json:"action,omitempty" xml:"action"`
	// Comments string.
	Comments string `json:"comments,omitempty" xml:"comments"`
	// Collection of Network objects identified by the name or UID. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	Destination []ApiObjectStandardIdentifier `json:"destination,omitempty" xml:"destination"`
	// True if negate is set for destination.
	DestinationNegate bool `json:"destination-negate,omitempty" xml:"destination-negate"`
	Domain *ApiDomainIdentifier `json:"domain,omitempty" xml:"domain"`
	// Enable/Disable the rule.
	Enabled bool `json:"enabled,omitempty" xml:"enabled"`
	// The rule's exceptions.
	Exceptions *interface{} `json:"exceptions,omitempty" xml:"exceptions"`
	// Which gateway, identified by the name or UID, to install the policy. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	InstallOn []ApiObjectStandardIdentifier `json:"install-on,omitempty" xml:"install-on"`
	// N/A
	Layer string `json:"layer,omitempty" xml:"layer"`
	MetaInfo *MetaInfoForTopLevelReply `json:"meta-info,omitempty" xml:"meta-info"`
	// Object name. Should be unique in the domain.
	Name string `json:"name,omitempty" xml:"name"`
	// Collection of network objects defining Protection Scope identified by the name or UID. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	ProtectedScope []ApiObjectStandardIdentifier `json:"protected-scope,omitempty" xml:"protected-scope"`
	// True if negate is set for Protected Scope.
	ProtectedScopeNegate bool `json:"protected-scope-negate,omitempty" xml:"protected-scope-negate"`
	// Collection of network objects defining Service identified by the name or UID. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	Service []ApiObjectStandardIdentifier `json:"service,omitempty" xml:"service"`
	// True if negate is set for Service.
	ServiceNegate bool `json:"service-negate,omitempty" xml:"service-negate"`
	// Collection of network objects defining Source identified by the name or UID. How much details are returned depends on the details-level field of the request. This table shows the level of detail shown when details-level is set to standard.
	Source []ApiObjectStandardIdentifier `json:"source,omitempty" xml:"source"`
	// True if negate is set for source.
	SourceNegate bool `json:"source-negate,omitempty" xml:"source-negate"`
	Track *ApiObjectStandardIdentifier `json:"track,omitempty" xml:"track"`
	TrackSettings *ThreatRuleTrackSettingsReply `json:"track-settings,omitempty" xml:"track-settings"`
	// Type of the object.
	Type_ string `json:"type,omitempty" xml:"type"`
	// Object unique identifier.
	Uid string `json:"uid,omitempty" xml:"uid"`
}
