/*
 * Check Point Management API
 *
 * Generated by https://github.com/janschumann/checkpoint-go-sdk.
 *
 * API version: v1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccessSectionIdentifierRequest struct {
	// The level of detail for some of the fields in the response can vary from showing only the UID value of the object to a fully detailed representation of the object.
	DetailsLevel string `json:"details-level,omitempty" xml:"details-level"`
	// Layer that the rule belongs to identified by the name or UID.
	Layer string `json:"layer" xml:"layer"`
	// Object name.
	Name string `json:"name,omitempty" xml:"name"`
	// Object unique identifier.
	Uid string `json:"uid" xml:"uid"`
}
